// Installs the tracked TypeScript git hooks (scripts/<hook>.ts) by writing a
// tiny shell shim into .git/hooks for each one.
//
// Why a shim instead of a symlink: git runs an extensionless hook file, but
// Node only strips TypeScript types for a `.ts` entry point — so the shim
// execs `node <hook>.ts`, where the extension is intact.
//
// Run via the package.json "postinstall" script. Idempotent and intentionally
// non-fatal: a missing .git, a permission error, or a pre-existing foreign hook
// can't fail `npm install`.
import {
	chmodSync,
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HOOKS = ["pre-commit"];
const MARKER = "generated by scripts/install-hooks.ts";

const contains = (path: string, needle: string): boolean => {
	try {
		return readFileSync(path, "utf8").includes(needle);
	} catch {
		return false;
	}
};

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const gitDir = join(root, ".git");

// Not a git checkout (e.g. installed from a tarball) — nothing to wire up.
if (existsSync(gitDir)) {
	const hooksDir = join(gitDir, "hooks");

	for (const hook of HOOKS) {
		const logic = join(root, "scripts", `${hook}.ts`);
		const dest = join(hooksDir, hook);
		if (!existsSync(logic)) continue;

		try {
			if (existsSync(dest) && !contains(dest, MARKER)) {
				console.warn(
					`hooks: .git/hooks/${hook} exists and isn't ours — leaving it alone`,
				);
				continue;
			}

			mkdirSync(hooksDir, { recursive: true });

			// Resolve the repo root at run time so the shim survives the repo
			// being moved. `|| true` keeps a failed/unsupported node (no TS type
			// stripping) from ever blocking a commit.
			const shim = [
				"#!/bin/sh",
				`# ${MARKER} — do not edit; regenerated on install`,
				'root="$(git rev-parse --show-toplevel)" || exit 0',
				`node "$root/scripts/${hook}.ts" "$@" || true`,
				"",
			].join("\n");

			writeFileSync(dest, shim);
			chmodSync(dest, 0o755);
			console.log(`hooks: installed .git/hooks/${hook}`);
		} catch (error) {
			console.warn(
				`hooks: could not install ${hook}: ${(error as Error).message}`,
			);
		}
	}
}
